name: Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Use Node.js 8.x
        uses: actions/setup-node@v4
        with:
          node-version: 8.x

      - run: npm ci
      - run: npm run grunt -- test:node
      - run: npm run grunt -- test:browser:local
